# wrangler.toml
name = "firestpre-upload-backup-be"
type = "javascript"
compatibility_date = "2024-09-23"
main = "src/index.js"

[dev]
port = 8787

[env.production]
vars = { ENVIRONMENT = "production" }